const OrderTypes = {
    ORDER_CREATE_REQUEST : 'ORDER_CREATE_REQUEST',
    ORDER_CREATE_SUCCESS : 'ORDER_CREATE_SUCCESS',
    ORDER_CREATE_FAIL : 'ORDER_CREATE_FAIL',
    ORDER_CREATE_RESET : 'ORDER_CREATE_RESET',

    ORDER_DETAIL_REQUEST : 'ORDER_DETAIL_REQUEST',
    ORDER_DETAIL_SUCCESS : 'ORDER_DETAIL_SUCCESS',
    ORDER_DETAIL_FAIL : 'ORDER_DETAIL_FAIL',

    ORDER_PAY_REQUEST : 'ORDER_PAY_REQUEST',
    ORDER_PAY_SUCCESS : 'ORDER_PAY_SUCCESS',
    ORDER_PAY_FAIL : 'ORDER_PAY_FAIL',
    ORDER_PAY_RESET : 'ORDER_PAY_RESET',

    ORDER_MYORDER_REQUEST : 'ORDER_MYORDER_REQUEST',
    ORDER_MYORDER_SUCCESS : 'ORDER_MYORDER_SUCCESS',
    ORDER_MYORDER_FAIL : 'ORDER_MYORDER_FAIL',
    ORDER_MYORDER_RESET : 'ORDER_MYORDER_RESET',

    ORDER_LIST_REQUEST : 'ORDER_LIST_REQUEST',
    ORDER_LIST_SUCCESS : 'ORDER_LIST_SUCCESS',
    ORDER_LIST_FAIL : 'ORDER_LIST_FAIL',
    ORDER_LIST_RESET : 'ORDER_LIST_RESET',

    ORDER_DELIVERED_REQUEST : 'ORDER_DELIVERED_REQUEST',
    ORDER_DELIVERED_SUCCESS : 'ORDER_DELIVERED_SUCCESS',
    ORDER_DELIVERED_FAIL : 'ORDER_DELIVERED_FAIL',
    ORDER_DELIVERED_RESET : 'ORDER_DELIVERED_RESET',
}
export default OrderTypes;